# Generated by Django 3.1 on 2020-08-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
