# Generated by Django 3.1 on 2020-08-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutForm',
        ),
        migrations.AddField(
            model_name='transaction',
            name='courses',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='No', max_length=10),
        ),
    ]
