# Generated by Django 3.1 on 2020-08-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200831_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
