# Generated by Django 3.1 on 2020-08-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_transaction_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('paid', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='made_by',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid',
            field=models.CharField(max_length=10),
        ),
    ]
