# Generated by Django 3.1 on 2020-09-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200831_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='video',
            field=models.CharField(max_length=1000),
        ),
    ]
