# Generated by Django 3.1 on 2020-09-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200909_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Preview2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=50)),
                ('iframe', models.CharField(max_length=1000)),
            ],
        ),
    ]
