# Generated by Django 3.1 on 2020-09-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_preview1_preview2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preview2',
        ),
        migrations.RenameField(
            model_name='preview1',
            old_name='idname',
            new_name='head',
        ),
        migrations.AddField(
            model_name='preview1',
            name='iframe',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
