# Generated by Django 3.1 on 2020-09-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200927_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preview1',
            new_name='Preview',
        ),
    ]
