# Generated by Django 3.1 on 2020-09-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200928_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cour_desc',
            field=models.TextField(max_length=255),
        ),
    ]
