# Generated by Django 3.1 on 2020-09-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20200928_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='courses',
            name='cour_desc',
            field=models.TextField(max_length=1500),
        ),
    ]
