# Generated by Django 3.1 on 2020-09-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200928_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='head4',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preview',
            name='head5',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preview',
            name='img1',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preview',
            name='img2',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
