# Generated by Django 3.1 on 2020-09-28 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20200928_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
