# Generated by Django 3.1 on 2020-09-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20200928_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bought',
            name='number',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
